common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 321321

development:
  <<: *common
  database: development

test:
  <<: *common
  database: test

production:
  <<: *common
  database: production
